# Occam core modules configuration

# OK
mod 'account',
  :git => 'https://github.com/torrancew/puppet-account.git',
  :ref => 'd71e20b521f4cfe3015a188ef66942fed0ea6bc9'

mod 'apache',
  :git => 'https://github.com/puppetlabs/puppetlabs-apache.git',
  :ref => '4cf7709c48222018e1f547bf47a44bafe6b1a15c'

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt',
  :ref => '924e89289b93db60ef0f16a4e71579fa88e037a6'

mod 'concat',
  :git => 'https://github.com/puppetlabs/puppetlabs-concat.git',
  :ref => '721ce8873837dc1d5a48f0a8af44216e4bafe7f2'

mod 'datacat',
  :git => 'https://github.com/mmz-srf/puppet-datacat.git',
  :ref => '113332f7860ebda419f2fa23b32035014d35c24a'

mod 'dnsmasq',
  :git => 'https://github.com/saz/puppet-dnsmasq.git',
  :ref => 'b685667f43c03e2dc8b90c02892e60d76d349517'

mod 'elasticsearch',
  :git => 'https://github.com/elasticsearch/puppet-elasticsearch.git',
  :ref => '0.4.0'

mod 'firewall',
  :git => 'https://github.com/damjanek/puppetlabs-firewall',
  :ref => '90c73e749267618d44b77a8c6d6170a078ecd255'

mod 'file_concat',
  :git => 'https://github.com/electrical/puppet-lib-file_concat.git',
  :ref => '0.1.0'

mod 'git',
  :git => 'https://github.com/puppetlabs/puppetlabs-git',
  :ref => '3ab03f32facab72cebc7c5acd00d3b5715e46985'

mod 'inifile',
  :git => 'https://github.com/cprice-puppet/puppetlabs-inifile.git',
  :ref => '530b053f71c60837573899cd6a8b3c9ec13f7196'

mod 'logstash',
  :git => 'https://github.com/elasticsearch/puppet-logstash.git',
  :ref => '0.5.1'

mod 'mcollective',
  :git => 'https://github.com/puppetlabs/puppetlabs-mcollective.git',
  :ref => '9a029a2b7af1f19e51f22cd676bba3ee97d22437'

mod 'mongodb',
  :git => 'https://github.com/puppetlabs/puppetlabs-mongodb.git',
  :ref => '6edf91888f40194a5c9c8913df57339df40104f5'

mod 'ntp',
  :git => 'https://github.com/puppetlabs/puppetlabs-ntp.git',
  :ref => '74fc27a2028eed54545f04d2c20187665dc45be6'

mod 'postgresql',
  :git => 'https://github.com/puppetlabs/puppet-postgresql.git',
  :ref => 'e25efcfc2196c583f7ba6e4ca8347056eafdf79b'

mod 'puppet',
  :git => 'https://github.com/stephenrjohnson/puppetlabs-puppet.git',
  :ref => '4c2bfeb6239bd39fd1d1dad6ac71ff8cc19dbf4b'

mod 'puppetdb',
  :git => 'https://github.com/puppetlabs/puppetlabs-puppetdb',
  :ref => '1c94d83dce208e958ff9b2f285716318646537c5'

mod 'puppetdbquery',
  :git => 'https://github.com/dalen/puppet-puppetdbquery.git',
  :ref => 'f40a33a25a230a3b7d08a6abb5fa43a551c1868e'

mod 'puppi',
  :git => 'https://github.com/example42/puppi.git',
  :ref => '57a88e119cc405e3d24bb7439d3f54d98a605d21'

mod 'rabbitmq',
  :git => 'https://github.com/puppetlabs/puppetlabs-rabbitmq.git',
  :ref => 'a3f136eaf8cce59e63728017a47137e6c9520a6f'

mod 'ruby',
  :git => 'https://github.com/puppetlabs/puppetlabs-ruby',
  :ref => 'd563eef028c624e7aef25934282cc273501f143a'

mod 'staging',
  :git => 'https://github.com/nanliu/puppet-staging.git',
  :ref => '1a4ce6fc6a815960f799cda37f93f5aff8eda925'

mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib',
  :ref => '1ffd72daaaf21e71e762b6cd543043680bdb6694'

mod 'sudo',
  :git => 'https://github.com/saz/puppet-sudo.git',
  :ref => '0141854aad7849bb163647d75f74ae79989f1f52'

mod 'timezone',
  :git => 'https://github.com/saz/puppet-timezone.git',
  :ref => 'v3.1.1'

mod 'users',
  :git => 'https://github.com/damjanek/puppet-users',
  :ref => 'c86f678f596f65ae1d03547b084e4fda7c002e14'

mod 'vcsrepo',
  :git => 'https://github.com/puppetlabs/puppetlabs-vcsrepo.git',
  :ref => 'b0f655163696aea40813db54fd830387bfc7e499'

mod 'zabbix',
  :git => 'https://github.com/kswia/puppet-zabbix.git',
  :ref => 'feature/simplified'

mod 'network',
  :git => 'https://github.com/example42/puppet-network.git',
  :ref => 'v3.1.18'

mod 'stdmod',
  :git => 'https://github.com/stdmod/stdmod.git',
  :ref => 'v0.0.4'
